language: generic 
sudo: required
services:
  - docker
before_install: 
  - docker build -t jdutama/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jdutama/docker-react npm run test -- --coverage
